version: '3.9'

services:
  writer:
    image: writer:v0.1
    container_name: writer
    build:
      context: .
      dockerfile: Dockerfile.writer
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    volumes:
      - ./files:/usr/src/app/files
  reader:
    image: reader:v0.1
    container_name: reader
    build:
      context: .
      dockerfile: Dockerfile.reader
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./files:/usr/src/app/files
