version: '3.9'

services:
  server:
    image: project:v0.5
    container_name: project-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./files:/usr/src/app/files
  images:
    image: images:v0.1
    container_name: images
    build:
      context: ./images
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    volumes:
      - ./files:/usr/src/app/files