version: '3.9'

services:
  server:
    image: project-server:v0.3
    container_name: project-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - 3001:3001

  client:
    image: project-client:v0.3
    container_name: project-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    