version: '3.9'

services:
  log-output:
    image: log-output:v0.3
    container_name: log-output
    build:
      context: ./log-output
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - 3001:3001